### ISSUE TITLE
IDV Demo App setup - username issue

### ISSUE THREAD

**Issue by andrasome** [aws-samples/amazon-rekognition-code-samples#32]
At the end of "identity-verification/module_1" there is the IDV Demo App solution.

Creating a new user allows the use upper case letters in the username, but the login part doesn't allow the use of upper case letters for the username and thus can't login.

**Comment by ConnorKirk** [comment]
Thanks for opening an issue @andrasome 

I have opened an issue with the repository that hosts the solution. I'm going to close the issue here, as there's nothing to be done on this repo.
